### ISSUE TITLE
Home empty

### ISSUE THREAD

**Issue by xdedeone** [onyxganda/dhyana-koken#1]
Hi. i use ur theme of base for my galery, the problem is in the home. is empty, i attach a image. can u help me please 
![issue](https://user-images.githubusercontent.com/7094130/34344160-7d5f7d68-e9b0-11e7-8910-0548d745be14.jpg)

**Comment by onyxcodes** [comment]
There's an issue actually, as for now the only way is to make sure you have featured_content (image or video) if not it won't load featured albums and essays in the home.

**Comment by xdedeone** [comment]
I fix it editing the cache.html in cache/site/index
For some reason the index in theme's folder dont is loading. Koken build the original index code, and editing the index.html don't work. But editing this cache html allows me to display albums in home whitout add this to featured_almbums.
Maybe u can fix it in next build?

**Comment by onyxcodes** [comment]
I see, gonna look into it. Although I don't' think it's a good idea to edit files outside the theme. Gonna find a better solution for the next build. 
Thanks!
